### PR TITLE
Add unset method to objects

### LINKED ISSUE #10: Deleting a key from an object
I haven't found a great way to delete a key from an object.  The best I've come up with is:
```
store = Store({ items: { a: 1, b: 2 } });
store = store.set('items', _.omit(store.items.toJS(), 'a'));
```

It works, but it feels clunky because of the need for the `toJS()`.  Is there a better way?

### PR DESCRIPTION
**Pull request by jrust**
`unset` will remove a key from an object and update paths. If the key
does not exist it will do nothing.

Fixes #10

### CODE REVIEW

**Comment by christianalfoni** [comment]
So sorry for the delay @jrust , but it is in now :-)

Btw, check out what I have been working on. It uses immutable-store as "engine". https://github.com/christianalfoni/cerebral

**Comment by jrust** [comment]
@christianalfoni - cerebral looks great!  Great to see innovation happening in this space.  Maybe I can figure out a `cerebral-angular` so we could use it on our project at work :smile:

**Comment by jrust** [comment]
Also, no rush, but when you get a chance could you push the new version up to flux-angular so that I can use it? Thanks!

**Comment by christianalfoni** [comment]
This has been fixed? Sorry for late reply, heh

**Comment by jrust** [comment]
Hmm, just looked and 2.4.0 still has an older version of immutable-store without this new functionality.

**Comment by christianalfoni** [comment]
Hi @jrust ,

Now it is updated :-) Btw, would you be interested checking out a project I am working on? It supports a package with Angular and Immutable-Store. I think you will like it ;-)

Package repo:
https://github.com/christianalfoni/cerebral-angular-immutable-store

Main repo:
https://github.com/christianalfoni/cerebral

**Comment by jrust** [comment]
Thanks @christianalfoni I'll check it out!  Looks really exciting, esp with the changes coming in angular 2.

**Pull request merged**
